In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.5 MB 9.1 MB/s 
     |████████████████████████████████| 182 kB 62.4 MB/s 
     |████████████████████████████████| 7.6 MB 52.0 MB/s 


In [ ]:
from transformers import AutoTokenizer, TFAutoModel

In [ ]:
clin_bert = TFAutoModel.from_pretrained("emilyalsentzer/Bio_ClinicalBERT", from_pt=True)

Downloading:   0%|          | 0.00/385 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy
import glob
import os
import keras
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.model_selection import KFold, StratifiedKFold
import matplotlib.pyplot as mp
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
import seaborn as sb
from sklearn.model_selection import cross_validate
from tensorflow.keras.callbacks import TensorBoard
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline, make_pipeline
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import RocCurveDisplay
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from matplotlib import pyplot
from sklearn.metrics import mean_absolute_error
import xgboost as xgb

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse

In [ ]:
import statistics
tf.random.set_seed(123)
from matplotlib import pyplot

In [ ]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
clin_bert

In [ ]:
df = pd.read_csv('case_training.csv')
df = df.drop(df.columns[0], axis = 1)

In [ ]:
df

Age  weight  Male  SchedSkinMins  scheduled_case_duration  \
0     42  2220.8     0             90                      115   
1     38  3035.2     0             90                       90   
2     61  3556.8     1             65                       95   
3     57  2681.6     0             60                       60   
4     55  2625.6     0            120                      120   
..   ...     ...   ...            ...                      ...   
140   40  3488.0     1             60                       90   
141   42  3244.8     1            120                      120   
142   41  3577.6     1             85                       85   
143   64  2281.6     0            120                      120   
144   51  2368.0     0            150                      175   

     ABRAMS, REID ALLEN  HENTZEN, ERIC RICHARD  LEEK, BRYAN TERRY  \
0                     0                      0                  0   
1                     0                      0                  0   
2                     0                      0                  1   
3                     0                      0                  0   
4                     0                      0                  0   
..                  ...                    ...                ...   
140                   0                      0                  0   
141                   1                      0                  0   
142                   1                      0                  0   
143                   0                      0                  0   
144                   1                      0                  0   

     MEUNIER, MATTHEW JOHN  RECHNIC, MARK  ...  without  wood  work  \
0                        1              0  ...        0     0     0   
1                        1              0  ...        0     0     0   
2                        0              0  ...        0     0     0   
3                        1              0  ...        0     0     0   
4                        1              0  ...        0     0     0   
..                     ...            ...  ...      ...   ...   ...   
140                      1              0  ...        0     0     0   
141                      0              0  ...        0     0     0   
142                      0              0  ...        0     0     0   
143                      1              0  ...        0     0     0   
144                      0              0  ...        1     0     0   

     workstation  worse  worst  would  wrist  \
0              0      0      0      0      2   
1              0      0      0      0      2   
2              0      0      0      0      3   
3              0      0      0      0      2   
4              0      0      1      0      3   
..           ...    ...    ...    ...    ...   
140            0      0      0      0      3   
141            0      0      0      0      0   
142            0      0      0      0      3   
143            0      0      0      0      2   
144            0      0      0      0      3   

                                             bert_text  actual_case_duration  
0    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...                    69  
1    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...                   110  
2    Narrative & Impression EXAM DESCRIPTION: X-RAY...                   103  
3    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...                    70  
4    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...                    90  
..                                                 ...                   ...  
140  EXAM DESCRIPTION:  X-RAY WRIST COMPLETE MINIMU...                    76  
141  EXAM DESCRIPTION: X-RAY ELBOW 2 VIEWS - LEFT  ...                   162  
142  EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...                   111  
143  EXAM DESCRIPTION:  X-RAY WRIST COMPLETE MINIMU...                   102  
144  EXAM DESCRIPTION: CT RT UPPER EXTREMITY  CLINI...                   233  

[145

In [ ]:
list(df.columns)

['Age',
 'weight',
 'Male',
 'SchedSkinMins',
 'scheduled_case_duration',
 'ABRAMS, REID ALLEN',
 'HENTZEN, ERIC RICHARD',
 'LEEK, BRYAN TERRY',
 'MEUNIER, MATTHEW JOHN',
 'RECHNIC, MARK',
 'Healthy',
 'Mild Systemic Disease',
 'Severe Systemic Disease',
 'Choice Per Patient on Day of Surgery',
 'General',
 'Monitored Anesthesia Care (MAC) ',
 'Regional',
 'height',
 '00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '104',
 '105',
 '108',
 '11',
 '116',
 '12',
 '1204',
 '121',
 '13',
 '1354',
 '138',
 '14',
 '140',
 '15',
 '16',
 '160',
 '1640',
 '17',
 '174',
 '18',
 '1814',
 '188',
 '19',
 '191',
 '1930',
 '196',
 '1st',
 '20',
 '2001',
 '2015',
 '2017',
 '2018',
 '2019',
 '2020',
 '21',
 '211',
 '2139',
 '22',
 '223',
 '2236',
 '228',
 '23',
 '2306',
 '24',
 '242',
 '244',
 '249',
 '25',
 '26',
 '262',
 '27',
 '270',
 '28',
 '284',
 '29',
 '297',
 '2nd',
 '30',
 '306',
 '307',
 '31',
 '32',
 '33',
 '330',
 '332',
 '34',
 '346',
 '35',
 '36',
 '360',
 '363'

In [ ]:
X = df.iloc[:, : 18]

In [ ]:
X

Age  weight  Male  SchedSkinMins  scheduled_case_duration  \
0     42  2220.8     0             90                      115   
1     38  3035.2     0             90                       90   
2     61  3556.8     1             65                       95   
3     57  2681.6     0             60                       60   
4     55  2625.6     0            120                      120   
..   ...     ...   ...            ...                      ...   
140   40  3488.0     1             60                       90   
141   42  3244.8     1            120                      120   
142   41  3577.6     1             85                       85   
143   64  2281.6     0            120                      120   
144   51  2368.0     0            150                      175   

     ABRAMS, REID ALLEN  HENTZEN, ERIC RICHARD  LEEK, BRYAN TERRY  \
0                     0                      0                  0   
1                     0                      0                  0   
2                     0                      0                  1   
3                     0                      0                  0   
4                     0                      0                  0   
..                  ...                    ...                ...   
140                   0                      0                  0   
141                   1                      0                  0   
142                   1                      0                  0   
143                   0                      0                  0   
144                   1                      0                  0   

     MEUNIER, MATTHEW JOHN  RECHNIC, MARK  Healthy  Mild Systemic Disease  \
0                        1              0        0                      0   
1                        1              0        0                      1   
2                        0              0        0                      1   
3                        1              0        0                      1   
4                        1              0        1                      0   
..                     ...            ...      ...                    ...   
140                      1              0        0                      1   
141                      0              0        1                      0   
142                      0              0        0                      1   
143                      1              0        0                      1   
144                      0              0        0                      1   

     Severe Systemic Disease  Choice Per Patient on Day of Surgery  General  \
0                          1                                     0        1   
1                          0                                     0        1   
2                          0                                     0        1   
3                          0                                     0        0   
4                          0                                     0        0   
..                       ...                                   ...      ...   
140                        0                                     0        1   
141                        0                                     0        0   
142                        0                                     1        0   
143                        0                                     0        0   
144                        0                                     0        0   

     Monitored Anesthesia Care (MAC)   Regional  height  
0                                   0         0  62.500  
1                                   0         0  59.000  
2                                   0         0  66.000  
3                                   0         1  65.000  
4                                   0         1  64.000  
..                                ...       ...     ...  
140                                 0         0  69.000  
141                                 0        

In [ ]:
X['bert'] = df['bert_text']

In [ ]:
X

Age  weight  Male  SchedSkinMins  scheduled_case_duration  \
0     42  2220.8     0             90                      115   
1     38  3035.2     0             90                       90   
2     61  3556.8     1             65                       95   
3     57  2681.6     0             60                       60   
4     55  2625.6     0            120                      120   
..   ...     ...   ...            ...                      ...   
140   40  3488.0     1             60                       90   
141   42  3244.8     1            120                      120   
142   41  3577.6     1             85                       85   
143   64  2281.6     0            120                      120   
144   51  2368.0     0            150                      175   

     ABRAMS, REID ALLEN  HENTZEN, ERIC RICHARD  LEEK, BRYAN TERRY  \
0                     0                      0                  0   
1                     0                      0                  0   
2                     0                      0                  1   
3                     0                      0                  0   
4                     0                      0                  0   
..                  ...                    ...                ...   
140                   0                      0                  0   
141                   1                      0                  0   
142                   1                      0                  0   
143                   0                      0                  0   
144                   1                      0                  0   

     MEUNIER, MATTHEW JOHN  RECHNIC, MARK  Healthy  Mild Systemic Disease  \
0                        1              0        0                      0   
1                        1              0        0                      1   
2                        0              0        0                      1   
3                        1              0        0                      1   
4                        1              0        1                      0   
..                     ...            ...      ...                    ...   
140                      1              0        0                      1   
141                      0              0        1                      0   
142                      0              0        0                      1   
143                      1              0        0                      1   
144                      0              0        0                      1   

     Severe Systemic Disease  Choice Per Patient on Day of Surgery  General  \
0                          1                                     0        1   
1                          0                                     0        1   
2                          0                                     0        1   
3                          0                                     0        0   
4                          0                                     0        0   
..                       ...                                   ...      ...   
140                        0                                     0        1   
141                        0                                     0        0   
142                        0                                     1        0   
143                        0                                     0        0   
144                        0                                     0        0   

     Monitored Anesthesia Care (MAC)   Regional  height  \
0                                   0         0  62.500   
1                                   0         0  59.000   
2                                   0         0  66.000   
3                                   0         1  65.000   
4                                   0         1  64.000   
..                                ...       ...     ...   
140                                 0         0  69.000   
141                                 0

In [ ]:
cols = list(X.columns)

In [ ]:
cols[-1] = cols[0]
cols[0] = 'bert'

In [ ]:
X[cols]

bert  weight  Male  \
0    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...  2220.8     0   
1    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...  3035.2     0   
2    Narrative & Impression EXAM DESCRIPTION: X-RAY...  3556.8     1   
3    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...  2681.6     0   
4    EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...  2625.6     0   
..                                                 ...     ...   ...   
140  EXAM DESCRIPTION:  X-RAY WRIST COMPLETE MINIMU...  3488.0     1   
141  EXAM DESCRIPTION: X-RAY ELBOW 2 VIEWS - LEFT  ...  3244.8     1   
142  EXAM DESCRIPTION: X-RAY WRIST COMPLETE MINIMUM...  3577.6     1   
143  EXAM DESCRIPTION:  X-RAY WRIST COMPLETE MINIMU...  2281.6     0   
144  EXAM DESCRIPTION: CT RT UPPER EXTREMITY  CLINI...  2368.0     0   

     SchedSkinMins  scheduled_case_duration  ABRAMS, REID ALLEN  \
0               90                      115                   0   
1               90                       90                   0   
2               65                       95                   0   
3               60                       60                   0   
4              120                      120                   0   
..             ...                      ...                 ...   
140             60                       90                   0   
141            120                      120                   1   
142             85                       85                   1   
143            120                      120                   0   
144            150                      175                   1   

     HENTZEN, ERIC RICHARD  LEEK, BRYAN TERRY  MEUNIER, MATTHEW JOHN  \
0                        0                  0                      1   
1                        0                  0                      1   
2                        0                  1                      0   
3                        0                  0                      1   
4                        0                  0                      1   
..                     ...                ...                    ...   
140                      0                  0                      1   
141                      0                  0                      0   
142                      0                  0                      0   
143                      0                  0                      1   
144                      0                  0                      0   

     RECHNIC, MARK  Healthy  Mild Systemic Disease  Severe Systemic Disease  \
0                0        0                      0                        1   
1                0        0                      1                        0   
2                0        0                      1                        0   
3                0        0                      1                        0   
4                0        1                      0                        0   
..             ...      ...                    ...                      ...   
140              0        0                      1                        0   
141              0        1                      0                        0   
142              0        0                      1                        0   
143              0        0                      1                        0   
144              0        0                      1                        0   

     Choice Per Patient on Day of Surgery  General  \
0                                       0        1   
1                                       0        1   
2                                       0        1   
3                                       0        0   
4                                       0        0   
..                                    ...      ...   
140                                     0        1   
141                                     0        0   
142                                     1        0   
143                       

In [ ]:
X = X[cols]

In [ ]:
Y = df['actual_case_duration']

In [ ]:
Y

0       69
1      110
2      103
3       70
4       90
      ... 
140     76
141    162
142    111
143    102
144    233
Name: actual_case_duration, Length: 145, dtype: int64

In [ ]:
import scipy.stats

def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h
# https://stackoverflow.com/questions/15033511/compute-a-confidence-interval-from-sample-data

In [ ]:
import numpy as np

SEQ_LEN = 512  # we will cut/pad our sequences to a length of 50 tokens

def tokenize(sentence):
    tokens = tokenizer.encode_plus(sentence, max_length=SEQ_LEN,
                                   truncation=True, padding='max_length',
                                   add_special_tokens=True, return_attention_mask=True,
                                   return_token_type_ids=False, return_tensors='tf')
    return tokens['input_ids'], tokens['attention_mask']

# https://gist.github.com/jamescalam/95c7fe7779244015c99a60c7fb0fa722

In [ ]:
from tensorflow.keras.layers import concatenate
from keras import metrics

In [ ]:
df_test = pd.read_csv('case_testing.csv')

In [ ]:
X = df.iloc[:, : 18]
X['bert'] = df['bert_text']
cols = list(X.columns)
cols[-1] = cols[0]
cols[0] = 'bert'
X = X[cols]
Y = df['actual_case_duration']

kfold = KFold(n_splits=10)
rmse_scores = []
mse_scores = []
mae_scores = []
test_dataset=1
fold = 0
for train_idx, test_idx in kfold.split(X, Y):
    fold = fold + 1
    print(fold)
    x_train_f = X.iloc[train_idx]
    y_train_f = Y.iloc[train_idx]
    x_test_f = X.iloc[test_idx]
    y_test_f = Y.iloc[test_idx]

    #print(len(x_test_f))
    
    # tokenize all text
    Xids_train = np.zeros((len(x_train_f), SEQ_LEN))
    Xmask_train = np.zeros((len(x_train_f), SEQ_LEN))
    
    Xids_test = np.zeros((len(x_test_f), SEQ_LEN))
    Xmask_test = np.zeros((len(x_test_f), SEQ_LEN))
    
    for i, sentence in enumerate(x_train_f[x_train_f.columns[0]]):
        Xids_train[i, :], Xmask_train[i, :] = tokenize(sentence)
    
    for i, sentence in enumerate(x_test_f[x_test_f.columns[0]]):
        Xids_test[i, :], Xmask_test[i, :] = tokenize(sentence)
        
    # make tf train dataset
    labels = y_train_f
    f1 = x_train_f[x_train_f.columns[1]]
    f2 = x_train_f[x_train_f.columns[2]]
    f3 = x_train_f[x_train_f.columns[3]]
    f4 = x_train_f[x_train_f.columns[4]]
    f5 = x_train_f[x_train_f.columns[5]]
    f6 = x_train_f[x_train_f.columns[6]]
    f7 = x_train_f[x_train_f.columns[7]]
    f8 = x_train_f[x_train_f.columns[8]]
    f9 = x_train_f[x_train_f.columns[9]]
    f10 = x_train_f[x_train_f.columns[10]]
    f11 = x_train_f[x_train_f.columns[11]]
    f12 = x_train_f[x_train_f.columns[12]]
    f13 = x_train_f[x_train_f.columns[13]]
    f14 = x_train_f[x_train_f.columns[14]]
    f15 = x_train_f[x_train_f.columns[15]]
    f16 = x_train_f[x_train_f.columns[16]]
    f17 = x_train_f[x_train_f.columns[17]]
    f18 = x_train_f[x_train_f.columns[18]]
    
    train_dataset = tf.data.Dataset.from_tensor_slices(( Xids_train, Xmask_train,
                                                          np.array(f1),
                                                          np.array(f2),
                                                          np.array(f3),
                                                          np.array(f4),
                                                          np.array(f5),
                                                          np.array(f6),
                                                          np.array(f7),
                                                          np.array(f8),
                                                          np.array(f9),
                                                          np.array(f10),
                                                          np.array(f11),
                                                          np.array(f12),
                                                          np.array(f13),
                                                          np.array(f14),
                                                          np.array(f15),
                                                          np.array(f16),
                                                          np.array(f17),
                                                          np.array(f18),
                                                          np.array(labels)))
    
    # make tf test dataset
    labels_test = y_test_f
    f1 = x_test_f[x_test_f.columns[1]]
    f2 = x_test_f[x_test_f.columns[2]]
    f3 = x_test_f[x_test_f.columns[3]]
    f4 = x_test_f[x_test_f.columns[4]]
    f5 = x_test_f[x_test_f.columns[5]]
    f6 = x_test_f[x_test_f.columns[6]]
    f7 = x_test_f[x_test_f.columns[7]]
    f8 = x_test_f[x_test_f.columns[8]]
    f9 = x_test_f[x_test_f.columns[9]]
    f10 = x_test_f[x_test_f.columns[10]]
    f11 = x_test_f[x_test_f.columns[11]]
    f12 = x_test_f[x_test_f.columns[12]]
    f13 = x_test_f[x_test_f.columns[13]]
    f14 = x_test_f[x_test_f.columns[14]]
    f15 = x_test_f[x_test_f.columns[15]]
    f16 = x_test_f[x_test_f.columns[16]]
    f17 = x_test_f[x_test_f.columns[17]]
    f18 = x_test_f[x_test_f.columns[18]]
    
    test_dataset = tf.data.Dataset.from_tensor_slices(( Xids_test, Xmask_test,
                                                          np.array(f1),
                                                          np.array(f2),
                                                          np.array(f3),
                                                          np.array(f4),
                                                          np.array(f5),
                                                          np.array(f6),
                                                          np.array(f7),
                                                          np.array(f8),
                                                          np.array(f9),
                                                          np.array(f10),
                                                          np.array(f11),
                                                          np.array(f12),
                                                          np.array(f13),
                                                          np.array(f14),
                                                          np.array(f15),
                                                          np.array(f16),
                                                          np.array(f17),
                                                          np.array(f18),
                                                          np.array(labels_test)
                                                          ))
        
    def mapfunc(input_ids, masks, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, labels_in):
        return {'input_ids': input_ids, 'attention_mask': masks, 
            'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4, 'f5': f5, 'f6': f6, 'f7': f7, 'f8': f8, 
            'f9': f9, 'f10': f10, 'f11': f11, 'f12': f12, 'f13': f13, 'f14': f14, 'f15': f15, 'f16': f16, 
            'f17': f17, 'f18': f18}, labels_in
   # print(len(test_dataset))
    train_dataset = train_dataset.map(mapfunc)
    test_dataset = test_dataset.map(mapfunc)
  #  print(len(test_dataset))
    
    BATCH_SIZE = 8
    
    train_dataset = train_dataset.shuffle(100000).batch(BATCH_SIZE, drop_remainder=True)
    test_dataset = test_dataset.shuffle(100000).batch(BATCH_SIZE, drop_remainder=True)

 #   print(len(test_dataset))
    
    input_ids = tf.keras.layers.Input(shape=(512,), name='input_ids', dtype='int32')
    mask = tf.keras.layers.Input(shape=(512,), name='attention_mask', dtype='int32')

    
    embeddings = clin_bert(input_ids, attention_mask=mask)[0]


    X = tf.keras.layers.Flatten()(embeddings)
    X = tf.keras.Model(inputs={'input_ids': input_ids,'attention_mask': mask}, outputs=X)

    ff1 = tf.keras.layers.Input(shape=(1,), name='f1')
    ff2 = tf.keras.layers.Input(shape=(1,), name='f2')
    ff3 = tf.keras.layers.Input(shape=(1,), name='f3')
    ff4 = tf.keras.layers.Input(shape=(1,), name='f4')
    ff5 = tf.keras.layers.Input(shape=(1,), name='f5')
    ff6 = tf.keras.layers.Input(shape=(1,), name='f6')
    ff7 = tf.keras.layers.Input(shape=(1,), name='f7')
    ff8 = tf.keras.layers.Input(shape=(1,), name='f8')
    ff9 = tf.keras.layers.Input(shape=(1,), name='f9')
    ff10 = tf.keras.layers.Input(shape=(1,), name='f10')
    ff11 = tf.keras.layers.Input(shape=(1,), name='f11')
    ff12 = tf.keras.layers.Input(shape=(1,), name='f12')
    ff13 = tf.keras.layers.Input(shape=(1,), name='f13')
    ff14 = tf.keras.layers.Input(shape=(1,), name='f14')
    ff15 = tf.keras.layers.Input(shape=(1,), name='f15')
    ff16 = tf.keras.layers.Input(shape=(1,), name='f16')
    ff17 = tf.keras.layers.Input(shape=(1,), name='f17')
    ff18 = tf.keras.layers.Input(shape=(1,), name='f18')

    other_input = concatenate([ff1, ff2, ff3, ff4, ff5, ff6, ff7, ff8, ff9, ff10, ff11, ff12, ff13, ff14, ff15, ff16, ff17, ff18])

    Y = tf.keras.layers.Flatten()(other_input)
    Y = tf.keras.Model(inputs={'f1': ff1,'f2': ff2,'f3': ff3,'f4': ff4,'f5': ff5,'f6': ff6,'f7': ff7,'f8': ff8,
                               'f9': ff9,'f10': ff10,'f11': ff11,'f12': ff12,'f13': ff13,'f14': ff14,'f15': ff15, 
                               'f16': ff16,'f17': ff17,'f18': ff18}, outputs=Y)

    combined = concatenate([X.output, Y.output])

    z = tf.keras.layers.Dense(256, activation="relu")(combined)
    z = tf.keras.layers.Dense(128, activation="relu")(z)
    z = tf.keras.layers.Dense(1, activation="linear")(z)


    model = tf.keras.Model(inputs={'input_ids': input_ids,'attention_mask': mask, 'f1': ff1,'f2': ff2,'f3': ff3,
                                   'f4': ff4,'f5': ff5,'f6': ff6,'f7': ff7,'f8': ff8,'f9': ff9,'f10': ff10,
                                   'f11': ff11,'f12': ff12,'f13': ff13,'f14': ff14,'f15': ff15,'f16': ff16,
                                   'f17': ff17,'f18': ff18},
                                   outputs=z)

    model.layers[20].trainable = False

    opt = tf.keras.optimizers.Adam(learning_rate=0.00005, decay = 0.000001)                                    
    
    model.compile(loss='mean_absolute_error', optimizer=opt, metrics=[metrics.mean_squared_error,
                                                                         metrics.mean_absolute_error])
    
    history = model.fit(train_dataset,
                        validation_data=test_dataset, 
                        epochs=10)
    
    print(history.history.keys())
    print("mae:",history.history['val_mean_absolute_error'][-1])
    mae_scores.append(history.history['val_mean_absolute_error'][-1])
    print("mse:",history.history['val_mean_squared_error'][-1])
    mse_scores.append(history.history['val_mean_squared_error'][-1])
    print("rmse:",np.sqrt(history.history['val_mean_squared_error'][-1]))
    rmse_scores.append(np.sqrt(history.history['val_mean_squared_error'][-1]))
    
    del(X)
    del(Y)
    del(train_dataset)
    del(test_dataset)
    keras.backend.clear_session()
    del(model)
    del(history)
    del(z)
    del(opt)
    del(combined)
    del(x_train_f)
    del(y_train_f)
    del(x_test_f)
    del(y_test_f)

    X = df.iloc[:, : 18]
    X['bert'] = df['bert_text']
    cols = list(X.columns)
    cols[-1] = cols[0]
    cols[0] = 'bert'
    X = X[cols]
    Y = df['actual_case_duration']

1
Epoch 1/10
16/16 [==============================] - 20s 566ms/step - loss: 46.6489 - mean_squared_error: 3996.6333 - mean_absolute_error: 46.6489 - val_loss: 24.4380 - val_mean_squared_error: 813.8113 - val_mean_absolute_error: 24.4380
Epoch 2/10
16/16 [==============================] - 6s 385ms/step - loss: 26.3915 - mean_squared_error: 1530.7649 - mean_absolute_error: 26.3915 - val_loss: 27.0104 - val_mean_squared_error: 919.8987 - val_mean_absolute_error: 27.0104
Epoch 3/10
16/16 [==============================] - 6s 385ms/step - loss: 21.5999 - mean_squared_error: 941.9378 - mean_absolute_error: 21.5999 - val_loss: 29.7836 - val_mean_squared_error: 1279.8384 - val_mean_absolute_error: 29.7836
Epoch 4/10
16/16 [==============================] - 6s 389ms/step - loss: 18.4751 - mean_squared_error: 799.2047 - mean_absolute_error: 18.4751 - val_loss: 32.0392 - val_mean_squared_error: 1281.1172 - val_mean_absolute_error: 32.0392
Epoch 5/10
16/16 [==============================] - 6s 38

In [ ]:
print("mae_scores:", mean_confidence_interval(mae_scores))
print("mse_scores:", mean_confidence_interval(mse_scores))
print("rmse_scores:", mean_confidence_interval(rmse_scores))

mae_scores: (19.58965425491333, 15.773073885746182, 23.40623462408048)
mse_scores: (685.5358673095703, 471.6130029669391, 899.4587316522015)
rmse_scores: (25.61139956580403, 21.509459952669204, 29.71333917893886)


In [ ]:
rmse_scores = []
mse_scores = []
mae_scores = []

X = df.iloc[:, : 18]
X['bert'] = df['bert_text']
cols = list(X.columns)
cols[-1] = cols[0]
cols[0] = 'bert'
X = X[cols]
Y = df['actual_case_duration']

X_test = df_test.iloc[:, 1: 19]
X_test['bert'] = df_test['bert_text']
cols = list(X_test.columns)
cols[-1] = cols[0]
cols[0] = 'bert'
X_test = X_test[cols]
Y_test = df_test['actual_case_duration']

x_train_f = X
y_train_f = Y
x_test_f = X_test
y_test_f = Y_test

    
    # tokenize all text
Xids_train = np.zeros((len(x_train_f), SEQ_LEN))
Xmask_train = np.zeros((len(x_train_f), SEQ_LEN))
    
Xids_test = np.zeros((len(x_test_f), SEQ_LEN))
Xmask_test = np.zeros((len(x_test_f), SEQ_LEN))
    
for i, sentence in enumerate(x_train_f[x_train_f.columns[0]]):
    Xids_train[i, :], Xmask_train[i, :] = tokenize(sentence)
    
for i, sentence in enumerate(x_test_f[x_test_f.columns[0]]):
    Xids_test[i, :], Xmask_test[i, :] = tokenize(sentence)
        
    # make tf train dataset
labels = y_train_f
f1 = x_train_f[x_train_f.columns[1]]
f2 = x_train_f[x_train_f.columns[2]]
f3 = x_train_f[x_train_f.columns[3]]
f4 = x_train_f[x_train_f.columns[4]]
f5 = x_train_f[x_train_f.columns[5]]
f6 = x_train_f[x_train_f.columns[6]]
f7 = x_train_f[x_train_f.columns[7]]
f8 = x_train_f[x_train_f.columns[8]]
f9 = x_train_f[x_train_f.columns[9]]
f10 = x_train_f[x_train_f.columns[10]]
f11 = x_train_f[x_train_f.columns[11]]
f12 = x_train_f[x_train_f.columns[12]]
f13 = x_train_f[x_train_f.columns[13]]
f14 = x_train_f[x_train_f.columns[14]]
f15 = x_train_f[x_train_f.columns[15]]
f16 = x_train_f[x_train_f.columns[16]]
f17 = x_train_f[x_train_f.columns[17]]
f18 = x_train_f[x_train_f.columns[18]]
    
train_dataset = tf.data.Dataset.from_tensor_slices(( Xids_train, Xmask_train,
                                                          np.array(f1),
                                                          np.array(f2),
                                                          np.array(f3),
                                                          np.array(f4),
                                                          np.array(f5),
                                                          np.array(f6),
                                                          np.array(f7),
                                                          np.array(f8),
                                                          np.array(f9),
                                                          np.array(f10),
                                                          np.array(f11),
                                                          np.array(f12),
                                                          np.array(f13),
                                                          np.array(f14),
                                                          np.array(f15),
                                                          np.array(f16),
                                                          np.array(f17),
                                                          np.array(f18),
                                                          np.array(labels)))
    
# make tf test dataset
labels_test = y_test_f
f1 = x_test_f[x_test_f.columns[1]]
f2 = x_test_f[x_test_f.columns[2]]
f3 = x_test_f[x_test_f.columns[3]]
f4 = x_test_f[x_test_f.columns[4]]
f5 = x_test_f[x_test_f.columns[5]]
f6 = x_test_f[x_test_f.columns[6]]
f7 = x_test_f[x_test_f.columns[7]]
f8 = x_test_f[x_test_f.columns[8]]
f9 = x_test_f[x_test_f.columns[9]]
f10 = x_test_f[x_test_f.columns[10]]
f11 = x_test_f[x_test_f.columns[11]]
f12 = x_test_f[x_test_f.columns[12]]
f13 = x_test_f[x_test_f.columns[13]]
f14 = x_test_f[x_test_f.columns[14]]
f15 = x_test_f[x_test_f.columns[15]]
f16 = x_test_f[x_test_f.columns[16]]
f17 = x_test_f[x_test_f.columns[17]]
f18 = x_test_f[x_test_f.columns[18]]
    
test_dataset = tf.data.Dataset.from_tensor_slices(( Xids_test, Xmask_test,
                                                          np.array(f1),
                                                          np.array(f2),
                                                          np.array(f3),
                                                          np.array(f4),
                                                          np.array(f5),
                                                          np.array(f6),
                                                          np.array(f7),
                                                          np.array(f8),
                                                          np.array(f9),
                                                          np.array(f10),
                                                          np.array(f11),
                                                          np.array(f12),
                                                          np.array(f13),
                                                          np.array(f14),
                                                          np.array(f15),
                                                          np.array(f16),
                                                          np.array(f17),
                                                          np.array(f18),
                                                          np.array(labels_test)
                                                          ))
        
def mapfunc(input_ids, masks, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, labels_in):
    return {'input_ids': input_ids, 'attention_mask': masks, 
            'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4, 'f5': f5, 'f6': f6, 'f7': f7, 'f8': f8, 
            'f9': f9, 'f10': f10, 'f11': f11, 'f12': f12, 'f13': f13, 'f14': f14, 'f15': f15, 'f16': f16, 
            'f17': f17, 'f18': f18}, labels_in
train_dataset = train_dataset.map(mapfunc)
test_dataset = test_dataset.map(mapfunc)
    
BATCH_SIZE = 8
    
train_dataset = train_dataset.shuffle(100000, reshuffle_each_iteration=False).batch(BATCH_SIZE, drop_remainder=True)
test_dataset = test_dataset.shuffle(100000, reshuffle_each_iteration=False).batch(BATCH_SIZE, drop_remainder=True)

    
input_ids = tf.keras.layers.Input(shape=(512,), name='input_ids', dtype='int32')
mask = tf.keras.layers.Input(shape=(512,), name='attention_mask', dtype='int32')

    
embeddings = clin_bert(input_ids, attention_mask=mask)[0]
clin_bert.trainable=False

X = tf.keras.layers.Flatten()(embeddings)
X = tf.keras.Model(inputs={'input_ids': input_ids,'attention_mask': mask}, outputs=X)

ff1 = tf.keras.layers.Input(shape=(1,), name='f1')
ff2 = tf.keras.layers.Input(shape=(1,), name='f2')
ff3 = tf.keras.layers.Input(shape=(1,), name='f3')
ff4 = tf.keras.layers.Input(shape=(1,), name='f4')
ff5 = tf.keras.layers.Input(shape=(1,), name='f5')
ff6 = tf.keras.layers.Input(shape=(1,), name='f6')
ff7 = tf.keras.layers.Input(shape=(1,), name='f7')
ff8 = tf.keras.layers.Input(shape=(1,), name='f8')
ff9 = tf.keras.layers.Input(shape=(1,), name='f9')
ff10 = tf.keras.layers.Input(shape=(1,), name='f10')
ff11 = tf.keras.layers.Input(shape=(1,), name='f11')
ff12 = tf.keras.layers.Input(shape=(1,), name='f12')
ff13 = tf.keras.layers.Input(shape=(1,), name='f13')
ff14 = tf.keras.layers.Input(shape=(1,), name='f14')
ff15 = tf.keras.layers.Input(shape=(1,), name='f15')
ff16 = tf.keras.layers.Input(shape=(1,), name='f16')
ff17 = tf.keras.layers.Input(shape=(1,), name='f17')
ff18 = tf.keras.layers.Input(shape=(1,), name='f18')

other_input = concatenate([ff1, ff2, ff3, ff4, ff5, ff6, ff7, ff8, ff9, ff10, ff11, ff12, ff13, ff14, ff15, ff16, ff17, ff18])

Y = tf.keras.layers.Flatten()(other_input)
Y = tf.keras.Model(inputs={'f1': ff1,'f2': ff2,'f3': ff3,'f4': ff4,'f5': ff5,'f6': ff6,'f7': ff7,'f8': ff8,
                               'f9': ff9,'f10': ff10,'f11': ff11,'f12': ff12,'f13': ff13,'f14': ff14,'f15': ff15, 
                               'f16': ff16,'f17': ff17,'f18': ff18}, outputs=Y)

combined = concatenate([X.output, Y.output])

z = tf.keras.layers.Dense(256, activation="relu")(combined)
z = tf.keras.layers.Dense(128, activation="relu")(z)
z = tf.keras.layers.Dense(1, activation="linear")(z)

model = tf.keras.Model(inputs={'input_ids': input_ids,'attention_mask': mask, 'f1': ff1,'f2': ff2,'f3': ff3,
                                   'f4': ff4,'f5': ff5,'f6': ff6,'f7': ff7,'f8': ff8,'f9': ff9,'f10': ff10,
                                   'f11': ff11,'f12': ff12,'f13': ff13,'f14': ff14,'f15': ff15,'f16': ff16,
                                   'f17': ff17,'f18': ff18},
                                   outputs=z)

model.summary()
model.layers[20].trainable = False

opt = tf.keras.optimizers.Adam(learning_rate=0.00005, decay = 0.000001)
    
model.compile(loss='mean_absolute_error', optimizer=opt, metrics=[metrics.mean_squared_error,
                                                                         metrics.mean_absolute_error])
    
history = model.fit(train_dataset,
                        validation_data=test_dataset, 
                        epochs=10)

preds = model.predict(test_dataset)
preds = [t[0] for t in preds]
# final
del(X)
del(Y)
del(train_dataset)
keras.backend.clear_session()
del(model)
del(history)
del(z)
del(opt)
del(combined)

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 f1 (InputLayer)                [(None, 1)]          0           []                               
                                                                                                  
 f2 (InputLayer)                [(None, 1)]          0           []                               
                                                                                            

In [ ]:
preds

[89.342575,
 84.96334,
 73.85574,
 89.143105,
 74.004524,
 89.45623,
 100.072495,
 102.35107,
 62.37254,
 90.96574,
 118.32195,
 111.199905,
 122.317406,
 106.99516,
 84.8193,
 69.322365,
 83.56809,
 116.3028,
 102.3071,
 67.5948,
 99.52764,
 112.82618,
 97.93588,
 60.369976,
 101.93672,
 98.007835,
 111.98784,
 114.860405,
 79.936325,
 64.58143,
 78.6915,
 77.065025,
 117.50474,
 107.42674,
 83.88853,
 101.741875,
 80.27219,
 76.06034,
 86.25531,
 109.2905,
 129.69717,
 68.16295,
 87.04166,
 85.51395,
 110.27611,
 99.25715,
 79.004684,
 89.421646,
 85.628296,
 90.18194,
 90.29712,
 89.49869,
 92.2751,
 82.29098,
 83.80102,
 86.92345]

In [ ]:
list(test_dataset)

[({'input_ids': <tf.Tensor: shape=(8, 512), dtype=float64, numpy=
   array([[  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          ...,
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101.,   193.,   118., ...,     0.,     0.,     0.]])>,
   'attention_mask': <tf.Tensor: shape=(8, 512), dtype=float64, numpy=
   array([[1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          ...,
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.]])>,
   'f1': <tf.Tensor: shape=(8,), dtype=float64, numpy=
   array([3619.07, 3062.4 , 2244.8 , 3680.  , 2000.  , 3020.8 , 2640.  ,
          3024.  ])>,
   'f2': <tf.Tensor: shape=(8,), dtype=in

In [ ]:
list(test_dataset)

[({'input_ids': <tf.Tensor: shape=(8, 512), dtype=float64, numpy=
   array([[  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          ...,
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101., 12211.,  6136., ...,     0.,     0.,     0.],
          [  101.,   193.,   118., ...,     0.,     0.,     0.]])>,
   'attention_mask': <tf.Tensor: shape=(8, 512), dtype=float64, numpy=
   array([[1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          ...,
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.]])>,
   'f1': <tf.Tensor: shape=(8,), dtype=float64, numpy=
   array([3619.07, 3062.4 , 2244.8 , 3680.  , 2000.  , 3020.8 , 2640.  ,
          3024.  ])>,
   'f2': <tf.Tensor: shape=(8,), dtype=in

In [ ]:
baseline = [90,  90,  60, 115,  80,  85,  65, 100, 60, 90, 90, 85, 75, 90, 55, 90, 60,  85,  75,  90,  90, 115, 105,  65, 65, 90, 85, 95, 60, 90, 55, 85, 95,  95,  75,  15, 110,  75,  60, 100, 115,  60,  90, 105,  85, 100,  60,  90, 85,  60,  85, 140, 145,  60,  60,  95]

In [ ]:
correct = [108,  92, 107,  80, 119, 114,  94,  89, 74, 103, 104, 108,  97,  86,  77,  77, 94, 126, 114, 153, 128, 112,  97,  68, 82,  81, 108,  90,  71, 102,  93,  72, 88, 147,  96,  69,  87, 101,  82, 121, 140,  72, 115,  80, 132,  83,  74,  85, 91,  81, 123,  78,  66,  80,  94,  90]

In [ ]:
mae(preds, correct)

16.138039316449845

In [ ]:
mse(correct, preds)

463.7457526501909

In [ ]:
mse(correct, preds, squared=False)

21.534756851429528

In [ ]:
mse(baseline, correct)

866.9464285714286

In [ ]:
mse(correct, baseline, squared=False)

29.443954024067974